version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/internal/db/migrations:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
    networks:
      - backend-net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - backend-net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  backend-net:
    driver: bridge